Component/progress
aniftyco/nifty-ui pull request #15
Opened 2023-04-25 15:53 UTC by UsefulBroom

Changed requested (position is now value) 
Component should be good to go.

2023-04-25 17:39 UTC, joshmanders requested changes

2023-04-25 17:39 UTC, joshmanders commented on docs/pages/docs/components/progress.mdx
> +  <div>
These extra divs are unnecessary.

2023-04-25 17:39 UTC, joshmanders commented on packages/nifty-ui/src/components/Progress/index.tsx
> +      style={{ transform: 'translateZ(0)' }}
Here's an exercise for you, try to translate these styles into arbitrary tailwind classes, like maybe `translate-z-0` and then the other `translate-x-[...]` but this one may not work because it won't be recognized by Tailwind JIT.

2023-04-26 14:26 UTC, UsefulBroom commented on packages/nifty-ui/src/components/Progress/index.tsx
> +      style={{ transform: 'translateZ(0)' }}
I spent some time trying to do this but we need to compute the translate x value in the indicator.

2023-04-26 14:32 UTC, joshmanders requested changes

2023-04-26 14:32 UTC, joshmanders commented on packages/nifty-ui/src/components/Progress/index.tsx
> +        className={`bg-primary-dark dark:bg-primary-light w-full h-full rounded-full`}
```suggestion
        className="bg-primary-dark dark:bg-primary-light w-full h-full rounded-full"
```

2023-04-26 14:33 UTC, joshmanders approved these changes
LGTM 🚀

2023-04-26 14:33 UTC, merged